"""initial schema

Revision ID: 2b8de7c337ed
Revises:
Create Date: 2026-06-20 20:03:59.845154

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b8de7c337ed"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "abilities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_hidden", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "natures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("increased_stat", sa.String(length=50), nullable=True),
        sa.Column("decreased_stat", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pokemon",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("base_experience", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.Column("sprite_url", sa.String(length=255), nullable=True),
        sa.Column("artwork_url", sa.String(length=255), nullable=True),
        sa.Column("generation", sa.Integer(), nullable=True),
        sa.Column("is_legendary", sa.Boolean(), nullable=True),
        sa.Column("is_mythical", sa.Boolean(), nullable=True),
        sa.Column("hp", sa.Integer(), nullable=True),
        sa.Column("attack", sa.Integer(), nullable=True),
        sa.Column("defense", sa.Integer(), nullable=True),
        sa.Column("sp_attack", sa.Integer(), nullable=True),
        sa.Column("sp_defense", sa.Integer(), nullable=True),
        sa.Column("speed", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "moves",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("power", sa.Integer(), nullable=True),
        sa.Column("accuracy", sa.Integer(), nullable=True),
        sa.Column("pp", sa.Integer(), nullable=True),
        sa.Column("damage_class", sa.String(length=20), nullable=True),
        sa.Column("type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pokemon_abilities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pokemon_id", sa.Integer(), nullable=True),
        sa.Column("ability_id", sa.Integer(), nullable=True),
        sa.Column("is_hidden", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ability_id"],
            ["abilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pokemon_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pokemon_id", sa.Integer(), nullable=True),
        sa.Column("power_score", sa.Integer(), nullable=True),
        sa.Column("offensive_score", sa.Integer(), nullable=True),
        sa.Column("tank_score", sa.Integer(), nullable=True),
        sa.Column("meta_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pokemon_id"),
    )
    op.create_table(
        "pokemon_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pokemon_id", sa.Integer(), nullable=True),
        sa.Column("type_id", sa.Integer(), nullable=True),
        sa.Column("slot", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pokemon_moves",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pokemon_id", sa.Integer(), nullable=True),
        sa.Column("move_id", sa.Integer(), nullable=True),
        sa.Column("learn_method", sa.String(length=50), nullable=True),
        sa.Column("level_learned", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["move_id"],
            ["moves.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pokemon_moves")
    op.drop_table("pokemon_types")
    op.drop_table("pokemon_scores")
    op.drop_table("pokemon_abilities")
    op.drop_table("moves")
    op.drop_table("types")
    op.drop_table("pokemon")
    op.drop_table("natures")
    op.drop_table("abilities")
    # ### end Alembic commands ###
