"""add role scores to pokemon_scores

Revision ID: 58f9feb8f6d9
Revises: dce8f8179f07
Create Date: 2026-08-03 17:11:29.728101

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58f9feb8f6d9"
down_revision: str | None = "dce8f8179f07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pokemon_scores", sa.Column("attacker_score", sa.Float(), nullable=True)
    )
    op.add_column(
        "pokemon_scores", sa.Column("tank_role_score", sa.Float(), nullable=True)
    )
    op.add_column(
        "pokemon_scores", sa.Column("support_score", sa.Float(), nullable=True)
    )
    op.add_column(
        "pokemon_scores", sa.Column("sweeper_score", sa.Float(), nullable=True)
    )
    op.add_column(
        "pokemon_scores", sa.Column("versatility_score", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pokemon_scores", "versatility_score")
    op.drop_column("pokemon_scores", "sweeper_score")
    op.drop_column("pokemon_scores", "support_score")
    op.drop_column("pokemon_scores", "tank_role_score")
    op.drop_column("pokemon_scores", "attacker_score")
    # ### end Alembic commands ###
