"""add type_effectiveness table

Revision ID: dce8f8179f07
Revises: b3f1a2c45d8e
Create Date: 2026-07-23 15:49:32.346344

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dce8f8179f07"
down_revision: str | None = "b3f1a2c45d8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "type_effectiveness",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attacker_type_id", sa.Integer(), nullable=False),
        sa.Column("defender_type_id", sa.Integer(), nullable=False),
        sa.Column("multiplier", sa.Float(), nullable=False),
        sa.Column("from_generation", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attacker_type_id"],
            ["types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["defender_type_id"],
            ["types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attacker_type_id", "defender_type_id", "from_generation"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("type_effectiveness")
    # ### end Alembic commands ###
