properties
sonar.projectKey=mayandre95_Pokedex
sonar.organization=mayandre95
sonar.sources=api,etl,ml
sonar.tests=api/tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.exclusions=**/node_modules/**,frontend/**,data/**
