export const GAME_ORDER: string[] = [
  'red',
  'blue',
  'yellow',
  'gold',
  'silver',
  'crystal',
  'ruby',
  'sapphire',
  'emerald',
  'firered',
  'leafgreen',
  'diamond',
  'pearl',
  'platinum',
  'heartgold',
  'soulsilver',
  'black',
  'white',
  'black-2',
  'white-2',
  'x',
  'y',
  'omega-ruby',
  'alpha-sapphire',
  'sun',
  'moon',
  'ultra-sun',
  'ultra-moon',
  'sword',
  'shield',
  'scarlet',
  'violet',
]

export const GAME_FR: Record<string, string> = {
  red: 'Rouge',
  blue: 'Bleu',
  yellow: 'Jaune',
  gold: 'Or',
  silver: 'Argent',
  crystal: 'Cristal',
  ruby: 'Rubis',
  sapphire: 'Saphir',
  emerald: 'Émeraude',
  firered: 'Rouge Feu',
  leafgreen: 'Vert Feuille',
  diamond: 'Diamant',
  pearl: 'Perle',
  platinum: 'Platine',
  heartgold: 'Or HeartGold',
  soulsilver: 'Argent SoulSilver',
  black: 'Noir',
  white: 'Blanc',
  'black-2': 'Noir 2',
  'white-2': 'Blanc 2',
  x: 'X',
  y: 'Y',
  'omega-ruby': 'Rubis Oméga',
  'alpha-sapphire': 'Saphir Alpha',
  sun: 'Soleil',
  moon: 'Lune',
  'ultra-sun': 'Ultra-Soleil',
  'ultra-moon': 'Ultra-Lune',
  sword: 'Épée',
  shield: 'Bouclier',
  scarlet: 'Écarlate',
  violet: 'Violet',
}

export const GAME_REGION: Record<string, string> = {
  red: 'Kanto',
  blue: 'Kanto',
  yellow: 'Kanto',
  firered: 'Kanto',
  leafgreen: 'Kanto',
  gold: 'Johto',
  silver: 'Johto',
  crystal: 'Johto',
  heartgold: 'Johto',
  soulsilver: 'Johto',
  ruby: 'Hoenn',
  sapphire: 'Hoenn',
  emerald: 'Hoenn',
  'omega-ruby': 'Hoenn',
  'alpha-sapphire': 'Hoenn',
  diamond: 'Sinnoh',
  pearl: 'Sinnoh',
  platinum: 'Sinnoh',
  black: 'Unys',
  white: 'Unys',
  'black-2': 'Unys',
  'white-2': 'Unys',
  x: 'Kalos',
  y: 'Kalos',
  sun: 'Alola',
  moon: 'Alola',
  'ultra-sun': 'Alola',
  'ultra-moon': 'Alola',
  sword: 'Galar',
  shield: 'Galar',
  scarlet: 'Paldea',
  violet: 'Paldea',
}

export const REGION_BULBAPEDIA: Record<string, string> = {
  Kanto: 'https://bulbapedia.bulbagarden.net/wiki/Kanto',
  Johto: 'https://bulbapedia.bulbagarden.net/wiki/Johto',
  Hoenn: 'https://bulbapedia.bulbagarden.net/wiki/Hoenn',
  Sinnoh: 'https://bulbapedia.bulbagarden.net/wiki/Sinnoh',
  Unys: 'https://bulbapedia.bulbagarden.net/wiki/Unova',
  Kalos: 'https://bulbapedia.bulbagarden.net/wiki/Kalos',
  Alola: 'https://bulbapedia.bulbagarden.net/wiki/Alola',
  Galar: 'https://bulbapedia.bulbagarden.net/wiki/Galar',
  Paldea: 'https://bulbapedia.bulbagarden.net/wiki/Paldea',
}

export const VERSION_GROUP_ORDER: string[] = [
  'red-blue',
  'yellow',
  'gold-silver',
  'crystal',
  'ruby-sapphire',
  'emerald',
  'firered-leafgreen',
  'diamond-pearl',
  'platinum',
  'heartgold-soulsilver',
  'black-white',
  'black-2-white-2',
  'x-y',
  'omega-ruby-alpha-sapphire',
  'sun-moon',
  'ultra-sun-ultra-moon',
  'lets-go-pikachu-lets-go-eevee',
  'sword-shield',
  'brilliant-diamond-and-shining-pearl',
  'legends-arceus',
  'scarlet-violet',
]

export const VERSION_GROUP_FR: Record<string, string> = {
  'red-blue': 'Rouge / Bleu',
  yellow: 'Jaune',
  'gold-silver': 'Or / Argent',
  crystal: 'Cristal',
  'ruby-sapphire': 'Rubis / Saphir',
  emerald: 'Émeraude',
  'firered-leafgreen': 'Rouge Feu / Vert Feuille',
  'diamond-pearl': 'Diamant / Perle',
  platinum: 'Platine',
  'heartgold-soulsilver': 'Or HG / Argent SS',
  'black-white': 'Noir / Blanc',
  'black-2-white-2': 'Noir 2 / Blanc 2',
  'x-y': 'X / Y',
  'omega-ruby-alpha-sapphire': 'Rubis Ω / Saphir α',
  'sun-moon': 'Soleil / Lune',
  'ultra-sun-ultra-moon': 'Ultra-Soleil / Ultra-Lune',
  'lets-go-pikachu-lets-go-eevee': "Let's Go",
  'sword-shield': 'Épée / Bouclier',
  'brilliant-diamond-and-shining-pearl': 'Diamant Étin. / Perle Scint.',
  'legends-arceus': 'Légendes : Arceus',
  'scarlet-violet': 'Écarlate / Violet',
}
