export const ITEM_FR: Record<string, string> = {
  'fire-stone': 'Pierre Feu',
  'water-stone': 'Pierre Eau',
  'thunder-stone': 'Pierre Foudre',
  'leaf-stone': 'Pierre Plante',
  'moon-stone': 'Pierre Lune',
  'sun-stone': 'Pierre Soleil',
  'shiny-stone': 'Pierre Brillante',
  'dusk-stone': 'Pierre Nuit',
  'dawn-stone': 'Pierre Aube',
  'ice-stone': 'Pierre Glace',
  'oval-stone': 'Pierre Ronde',
  'kings-rock': 'Pierre des Rois',
  'metal-coat': 'Toge Métal',
  'dragon-scale': 'Écaille Draco',
  'up-grade': 'Mise à Niveau',
  'dubious-disc': 'Disque Douteux',
  electirizer: 'Électriseur',
  magmarizer: 'Magmariseur',
  protector: 'Protecteur',
  'reaper-cloth': 'Suaire Faucheur',
  'razor-claw': 'Griffe Rasoir',
  'prism-scale': 'Écaille Prisme',
  'whipped-dream': 'Nuage Sucré',
  sachet: 'Sachet Parfumé',
}
