export const LOCATION_AREA_FR: Record<string, string> = {
  // ── Kanto ─────────────────────────────────────────────────────────────
  'pallet-town-area': 'Bourg Palette',
  'viridian-city-area': 'Jadielle',
  'viridian-forest-area': 'Forêt de Jade',
  'pewter-city-area': 'Argenta',
  'cerulean-city-area': 'Azuria',
  'cerulean-cave-1f': 'Grotte Azurée 1F',
  'cerulean-cave-2f': 'Grotte Azurée 2F',
  'cerulean-cave-b1f': 'Grotte Azurée B1',
  'vermilion-city-area': 'Cramoisile',
  'vermilion-city-ss-anne-dock': 'Cramoisile – Quai du S.S. Anne',
  'lavender-town-area': 'Lavanville',
  'celadon-city-area': 'Céladopole',
  'celadon-city-prize-corner': 'Céladopole – Coin des Trophées',
  'fuchsia-city-area': 'Fuchsia',
  'saffron-city-area': 'Safrania',
  'cinnabar-island-area': "Cramois'Île",
  'mt-moon-mt-moon-square': 'Mont Sélénite',
  'seafoam-islands-b3f': 'Grottes Écume B3',
  'seafoam-islands-b4f': 'Grottes Écume B4',
  'icefall-cave-entrance': 'Grotte Glacefall (Entrée)',
  'icefall-cave-waterfall': 'Grotte Glacefall (Cascade)',
  'kanto-power-plant-area': 'Centrale',
  'kanto-safari-zone-area-1-east': 'Zone Safari Kanto 1 Est',
  'kanto-safari-zone-area-2-north': 'Zone Safari Kanto 2 Nord',
  'kanto-safari-zone-area-3-west': 'Zone Safari Kanto 3 Ouest',
  'kanto-safari-zone-middle': 'Zone Safari Kanto Centre',
  'pokemon-tower-area': 'Tour Pokémon',
  'pokemon-mansion-area': 'Manoir Pokémon',
  'altering-cave-area': 'Grotte Altérante',
  'cape-brink-area': 'Cap des Hauts',
  'five-island-area': 'Cinquième Île',
  'five-isle-meadow-area': 'Prairie Cinquième Île',
  'four-island-area': 'Quatrième Île',
  'green-path-area': 'Sentier Vert',
  'one-island-area': 'Première Île',
  'outcast-island-area': 'Île Banni',
  'pattern-bush-area': 'Buissons Bigarrés',
  'ruin-valley-area': 'Vallée des Ruines',
  'tanoby-ruins-area': 'Ruines Tanoby',
  'trainer-tower-area': 'Tour des Dresseurs',
  'treasure-beach-area': 'Plage aux Trésors',
  'water-labyrinth-area': 'Labyrinthe Aquatique',
  'water-path-area': 'Chemin Aquatique',
  'ss-anne-area': 'S.S. Anne',
  'bond-bridge-area': 'Pont Amitié',
  'kindle-road-area': 'Route Braise',
  'memorial-pillar-area': 'Stèle Mémorial',
  'resort-gorgeous-area': 'Hôtel de Luxe',

  // ── Johto ─────────────────────────────────────────────────────────────
  'new-bark-town-area': 'Bourg Ébène',
  'cherrygrove-city-area': 'Bois Joli',
  'violet-city-area': 'Violette',
  'azalea-town-area': 'Doublonville',
  'goldenrod-city-area': 'Dorado',
  'ecruteak-city-area': 'Ambre',
  'olivine-city-area': 'Oliville',
  'cianwood-city-area': 'Acajou',
  'mahogany-town-area': 'Acajou',
  'blackthorn-city-area': 'Sachinoé',
  'ilex-forest-area': 'Forêt Céladon',
  'national-park-area': 'Parc National',
  'lake-of-rage-area': 'Lac Colère',
  'ruins-of-alph-outside': 'Ruines Aborea (Ext.)',
  'tohjo-falls-area': 'Cascades Tohjo',
  'union-cave-1f': 'Grotte Symbiose 1F',
  'union-cave-b1f': 'Grotte Symbiose B1',
  'union-cave-b2f': 'Grotte Symbiose B2',
  'slowpoke-well-1f': 'Puits Ramoloss 1F',
  'slowpoke-well-b1f': 'Puits Ramoloss B1',
  'dark-cave-violet-city-entrance': 'Grotte Sombre (Violette)',
  'dark-cave-blackthorn-city-entrance': 'Grotte Sombre (Sachinoé)',
  'mt-mortar-1f': 'Mont Mortier 1F',
  'mt-mortar-b1f': 'Mont Mortier B1',
  'mt-mortar-upper-cave': 'Mont Mortier (Grotte Haute)',
  'ice-path-area': 'Chemin Glace',
  'dragons-den-area': 'Antre du Dragon',
  'whirl-islands-1f': 'Îles Tourbillon 1F',
  'whirl-islands-b2f': 'Îles Tourbillon B2',
  'whirl-islands-b3f': 'Îles Tourbillon B3',
  'mt-silver-outside': 'Mont Argent (Ext.)',
  'mt-silver-1f': 'Mont Argent 1F',
  'mt-silver-1f-top': 'Mont Argent 1F (Sommet)',
  'mt-silver-2f': 'Mont Argent 2F',
  'mt-silver-4f': 'Mont Argent 4F',
  'mt-silver-top': 'Mont Argent (Sommet)',
  'johto-safari-zone-wetland': 'Zone Safari Johto Zone Humide',
  'johto-safari-zone-meadow': 'Zone Safari Johto Prairie',
  'johto-safari-zone-marshland': 'Zone Safari Johto Marais',
  'johto-safari-zone-rocky-beach': 'Zone Safari Johto Plage',
  'johto-safari-zone-swamp': 'Zone Safari Johto Marécage',
  'johto-route-47-cave-gate': 'Route 47 (Porte Grotte)',

  // ── Hoenn ─────────────────────────────────────────────────────────────
  'littleroot-town-area': 'Bourg-en-Vol',
  'oldale-town-area': 'Bigleaf',
  'petalburg-city-area': 'Pétalia',
  'rustboro-city-area': 'Mérouville',
  'dewford-town-area': 'Doeton',
  'slateport-city-area': 'Brindibois',
  'mauville-city-area': 'Lampopolis',
  'verdanturf-town-area': 'Verdanvert',
  'fallarbor-town-area': 'Cendres',
  'lavaridge-town-area': 'Laverousse',
  'fortree-city-area': 'Arboville',
  'lilycove-city-area': 'Joliberges',
  'mossdeep-city-area': 'Illumis',
  'sootopolis-city-area': 'Blanche-Neige',
  'ever-grande-city-area': 'Granderoute',
  'petalburg-woods-area': 'Forêt Pétalia',
  'jagged-pass-area': 'Sentier Déchiré',
  'fiery-path-area': 'Chemin Ardent',
  'rusturf-tunnel-area': 'Tunnel Rocantin',
  'meteor-falls-area': 'Chute Météores',
  'meteor-falls-b1f': 'Chute Météores B1',
  'meteor-falls-back': 'Chute Météores (Fond)',
  'meteor-falls-backsmall-room': 'Chute Météores (Petite Salle)',
  'seafloor-cavern-area': 'Grotte Abyssale',
  'abandoned-ship-area': 'Épave Abandonnée',
  'pacifidlog-town-area': 'Pacifidlog',
  'ravaged-path-area': 'Chemin Dégradé',
  'hoenn-victory-road-b2f': 'Route Victoire B2',
  'hoenn-safari-zone-sw': 'Zone Safari Hoenn SO',
  'hoenn-safari-zone-se': 'Zone Safari Hoenn SE',
  'hoenn-safari-zone-expansion-south': 'Zone Safari Hoenn (Ext. Sud)',
  'hoenn-safari-zone-nwmach-bike-area': 'Zone Safari Hoenn (NO – Vélo)',
  'hoenn-pokecenter-area': 'Centre Pokémon Hoenn',
  'shoal-cave-high-tide': 'Grotte Méandre (Haute Mer)',
  'oreburgh-gate-b1f': 'Passage Minerais B1',

  // ── Sinnoh ────────────────────────────────────────────────────────────
  'twinleaf-town-area': 'Bonaugure',
  'sandgem-town-area': 'Littlebaie',
  'jubilife-city-area': 'Bonheurville',
  'oreburgh-city-area': 'Minerais',
  'floaroma-town-area': 'Floraville',
  'eterna-city-area': 'Vestigion',
  'hearthome-city-area': 'Concoeur',
  'solaceon-town-area': 'Bonheureux',
  'veilstone-city-area': 'Mélancolies',
  'pastoria-city-area': 'Marécages',
  'celestic-town-area': 'Célestia',
  'canalave-city-area': 'Corsept',
  'snowpoint-city-area': 'Blancneige',
  'sunyshore-city-area': 'Rivesol',
  'resort-area-area': 'Zone Relax',
  'eterna-forest-area': 'Forêt Vestige',
  'trophy-garden-area': 'Jardin Trophée',
  'great-marsh-area-1': 'Grand Marais 1',
  'great-marsh-area-2': 'Grand Marais 2',
  'great-marsh-area-3': 'Grand Marais 3',
  'great-marsh-area-4': 'Grand Marais 4',
  'great-marsh-area-5': 'Grand Marais 5',
  'great-marsh-area-6': 'Grand Marais 6',
  'fuego-ironworks-area': 'Aciérie Fuego',
  'lake-valor-area': 'Lac Valeur',
  'lake-verity-before-galactic-intervention': 'Lac Vérité (Avant Galactique)',
  'lake-verity-after-galactic-intervention': 'Lac Vérité (Après Galactique)',
  'lake-acuity-area': 'Lac Sérénité',
  'iron-island-area': 'Île Acier',
  'sendoff-spring-area': 'Source Adieu',
  'marvelous-bridge-area': 'Pont Merveilleux',
  'valley-windworks-area': 'Centrale du Vallon',
  'mt-coronet-1f-route-207': 'Mont Couronné 1F (R.207)',
  'mt-coronet-4f': 'Mont Couronné 4F',
  'mt-coronet-b1f': 'Mont Couronné B1',
  'sinnoh-victory-road-b1f': 'Route Victoire B1',
  'sinnoh-victory-road-inside-b1f': 'Route Victoire (Int.) B1',
  'sinnoh-pokemon-league-area': 'Ligue Pokémon',
  'unknown-all-poliwag-area': 'Zone Ptitard (Inconnu)',
  'unknown-all-rattata-area': 'Zone Rattata (Inconnu)',

  // ── Unova ─────────────────────────────────────────────────────────────
  'nuvema-town-area': 'Nuvéma',
  'accumula-town-area': 'Mélessa',
  'striaton-city-area': 'Mélodine',
  'nacrene-city-area': 'Nacropolis',
  'castelia-city-area': 'Castélia',
  'nimbasa-city-area': 'Nimbassa',
  'driftveil-city-area': 'Poudreige',
  'mistralton-city-area': 'Crackling',
  'icirrus-city-area': 'Glaciapolis',
  'opelucid-city-area': 'Dragionord',
  'lacunosa-town-area': 'Lacunosa',
  'undella-town-area': 'Littlebaie',
  'black-city-area': 'Ville Sombre',
  'white-forest-area': 'Forêt Blanche',
  'lostlorn-forest-area': 'Forêt Perdue',
  'abundant-shrine-area': 'Autel Abondance',

  // ── Kalos ─────────────────────────────────────────────────────────────
  'vaniville-town-area': 'Vanilland',
  'aquacorde-town-area': 'Aquacorde',
  'santalune-city-area': 'Papillia',
  'lumiose-city-area': 'Illumis',
  'camphrier-town-area': 'Camphre',
  'cyllage-city-area': 'Cysalmille',
  'ambrette-town-area': 'Magnolane',
  'geosenge-town-area': 'Géocisailles',
  'shalour-city-area': 'Alomolia',
  'coumarine-city-area': 'Coumarine',
  'laverre-city-area': 'Florushalt',
  'dendemille-town-area': 'Aromiflor',
  'anistar-city-area': 'Anistarfonds',
  'couriway-town-area': 'Beldurga',
  'snowbelle-city-area': 'Snowmard',
  'santalune-forest-area': 'Forêt de Papillia',
  'azure-bay-area': 'Baie Azurée',
  'lost-hotel-area': 'Hôtel Perdu',
  'pokemon-village-area': 'Village Pokémon',
  'friend-safari-area': 'Safari Ami',
  'friend-safari-electric': 'Safari Ami',
  'parfum-palace-area': 'Palais Parfum',

  // ── Alola ─────────────────────────────────────────────────────────────
  'hauoli-city-beachfront': 'Plage Iti City',
  'hauoli-city-shopping-district': 'Centre Commercial Iti City',
  'heahea-city-surf-association': "Association Surf d'Heuheua",
  'paniola-town-area': 'Ranch Paniola',
  'tapu-village-area': 'Village Tapu',
  'seafolk-village-main': 'Village Maritime',
  'kalae-bay-area': 'Baie Kala-e',
  'melemele-sea-area': 'Mer Méléméle',
  'brooklet-hill-north': 'Colline Ruisseau (Nord)',
  'brooklet-hill-south': 'Colline Ruisseau (Sud)',
  'brooklet-hill-totems-den': 'Colline Ruisseau (Antre du Totém)',
  'lush-jungle-area': 'Jungle Luxuriante',
  'wela-volcano-park-area': 'Parc Volcan Wela',
  'malie-garden-area': 'Jardin de Malie',
  'haina-desert-area': 'Désert Haïna',
  'vast-poni-canyon-northwest': 'Canyon Poni (NO)',
  'ancient-poni-path-area': 'Sentier Ancestral Poni',
  'poni-gauntlet-area': 'Épreuve Poni',
  'poni-wilds-area': 'Terres Sauvages Poni',
  'poni-meadow-area': 'Prairie Poni',
  'poni-breaker-coast-area': 'Côte Brise-Lames Poni',
  'poni-coast-area': 'Côte Poni',
  'nature-sanctuary-area': 'Sanctuaire Naturel',
  'exeggutor-island-area': 'Île Noadkoko',
  'blush-mountain-area': 'Mont Blush',
  'secluded-shore-area': 'Plage Isolée',
  'seaward-cave-area': 'Grotte Marine',
  'mount-lanakila-area': 'Mont Lanakila',
  'ruins-of-hope-area': 'Ruines Espoir',
  'resolution-cave-area': 'Grotte Résolution',
  'akala-outskirts-area': 'Périphérie Akala',
  'berry-fields-area': 'Champs Baies',
  'memorial-hill-area': 'Colline Mémorial',
  'meetup-spot-area': 'Zone de Rencontre',

  // ── Galar ─────────────────────────────────────────────────────────────
  'slumbering-weald-area': 'Forêt Assoupie',
  'slumbering-weald-deep': 'Forêt Assoupie (Profondeurs)',
  'motostoke-main': 'Motostoke',
  'glimwood-tangle-area': 'Bois Luisant',
  'watchtower-ruins-area': 'Ruines Tour de Guet',
  // Zone Naturelle
  'rolling-fields-main': 'Zone Naturelle – Plaine',
  'east-lake-axewell-area': 'Zone Naturelle – Lac Axell Est',
  'west-lake-axewell-area': 'Zone Naturelle – Lac Axell Ouest',
  'axews-eye-area': 'Zone Naturelle – Axell',
  'south-lake-miloch-main': 'Zone Naturelle – Lac Miloch Sud',
  'north-lake-miloch-area': 'Zone Naturelle – Lac Miloch Nord',
  'bridge-field-area': 'Zone Naturelle – Plaine-Pont',
  'stony-wilderness-main': 'Zone Naturelle – Désert Pierreux',
  'stony-wilderness-area-2': 'Zone Naturelle – Désert Pierreux 2',
  'stony-wilderness-area-3': 'Zone Naturelle – Désert Pierreux 3',
  'dusty-bowl-main': 'Zone Naturelle – Plaine Poussiéreuse',
  'giants-mirror-area': 'Zone Naturelle – Miroir du Géant',
  'hammerlocke-hills-area': 'Zone Naturelle – Collines Martelocker',
  'giants-cap-area': 'Zone Naturelle – Bonnet du Géant',
  'lake-of-outrage-area': 'Zone Naturelle – Lac Colère',
  'giants-seat-area': 'Zone Naturelle – Siège du Géant',
  'motostoke-riverbank-area': 'Zone Naturelle – Rive Motostoke',
  // Île Armure
  'fields-of-honor-area': 'Champs Honneur',
  'soothing-wetlands-area': 'Marécages Apaisants',
  'forest-of-focus-area': 'Forêt Concentration',
  'challenge-beach-area': 'Plage Challenge',
  'courageous-cavern-area': 'Grotte Courageuse',
  'loop-lagoon-area': 'Lagon Boucle',
  'workout-sea-area': "Mer d'Entraînement",
  'stepping-stone-sea-main': 'Mer des Pierres',
  'honeycalm-island-area': 'Île Doucemiel',
  'honeycalm-sea-area': 'Mer Doucemiel',
  'insular-sea-area': 'Mer Insulaire',
  'training-lowlands-area': 'Plaines Entraînement',
  // Toundra Couronnée
  'giant-bed-area': 'Lit du Géant',
  'old-cemetery-area': 'Vieux Cimetière',
  'snowslide-slope-area': 'Coulée de Neige',
  'frigid-sea-area': 'Mer Glaciale',
  'three-point-pass-area': 'Col Trois Pointes',
  'ballimere-lake-area': 'Lac Ballimere',
  'lakeside-cave-area': 'Grotte du Lac',
  'dyna-tree-hill-area': 'Colline Arbre Dyna',
  'max-lair-area': 'Antre Max',
}
